// RootLayout.jsx
"use client";
import { useState, useEffect } from "react";
import { FaSpinner } from "react-icons/fa"; // Import spinner icon for enhanced UI
import Navbar from "@/component/Navbar"; // Make sure to adjust imports if necessary
import "./globals.css"; // Import your custom global styles

export default function RootLayout({ children }) {
  const [loading, setLoading] = useState(true);

  // Simulate loading for demo purposes
  useEffect(() => {
    // Simulate a delay before content is loaded (remove this in production)
    setTimeout(() => {
      setLoading(false);
    }, 2000); // 2 seconds delay
  }, []);

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={`relative ${loading ? 'bg-black' : ''}`}>
        <header className={loading ? 'hidden' : ''}>
          <Navbar />
        </header>
        <main>
          {loading ? (
            <div className="absolute inset-0 flex justify-center items-center bg-black opacity-100 z-50">
              {/* Spinner in the center */}
              <FaSpinner className="animate-spin text-hoverUnderlineColor text-8xl sm:text-6xl sm:mt-[80%] md:text-7xl md:mt-[60%] lg:text-8xl lg:mt-[40%] mt-[90%]" />
              </div>
          ) : (
            // Render children once loading is complete
            children
          )}
        </main>
      </body>
    </html>
  );
}
